{% set name = "poselib" %}
{% set version = "2.0.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/PoseLib/PoseLib/archive/refs/tags/v{{ version }}.tar.gz
    sha256: a9493e6725c58e6ae541fe416c0a6179185a60006880ff3ddf32737a43695668
    patches:
      - unvendor_pybind11.patch
      - fix_windows.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('poselib', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make                                   # [unix]
    - ninja
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - pybind11-stubgen                       # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - pip
    - setuptools
    - python
    - pybind11
    - pybind11-stubgen
    - eigen
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - poselib
  commands:
    - pip check
    - if not exist %PREFIX%\\Library\\lib\\PoseLib.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\PoseLib\\PoseLibConfig.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\PoseLib\\poselib.h exit 1  # [win]
    - test -f ${PREFIX}/lib/libPoseLib${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/include/PoseLib/poselib.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/PoseLib/PoseLibConfig.cmake  # [unix]
  requires:
    - pip

about:
  home: https://github.com/PoseLib/PoseLib
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: PoseLib provides a collection of minimal solvers for camera pose estimation.

extra:
  recipe-maintainers:
    - Tobias-Fischer
